create table if not exists category (
    id integer generated by default as identity primary key,
    name varchar(100) not null
);

create table if not exists quote (
    id integer generated by default as identity primary key,
    text varchar(500) not null,
    author varchar(100) not null,
    category_id integer not null references category(id) on delete cascade
);

create index if not exists idx_quote_category_id on quote(category_id);
